### ISSUE TITLE
Not functioning properly on multiplayer servers.

### ISSUE THREAD

**Issue by ActualVoidDiver** [aleksilassila/litematica-printer#63] opened 2022-02-04 07:15 UTC
I attempted using Litematica-printer on a multiplayer server, once printer mode is enabled: only ghost-blocks are placed. Staff members of the server informed me that they did not do anything to attempt preventing players from using schematics printers, and so a staff member had told me they've done schematics printing through "Schematica", which I did try out, and functioned properly. Though, I prefer Litematica, and the schematics that I want to print are only available in Litematica file format. Have a nice day :>

**Comment by aleksilassila** [comment] 2022-02-04 13:15
Which server does this happen on, or is it on all servers? If they use anticheat plugin of some sort that checks for blocks that are placed directly in the air, that might be the cause. And if that's the case, it will be fixed in a future update.

**Comment by ActualVoidDiver** [comment] 2022-02-04 14:18
It did happen on a server that I decided to revisit: SkittleMC. I'm using version 2.1 of Litematica-printer, which I believe to be the latest version. I'm running both latest 1.16.5 Litematica-printer and Litematica. Schematica is able to print schematics in the server in-question, which I assume that Schematica printing functionality and Litematica printer mod. would be somewhat similar in functionality? And so the anti-cheat should also attempt blocking Schematica's printing functionality? I'm unsure.
I wish you a nice day :>

**Comment by beldinn** [comment] 2022-02-06 15:19
Hi,
Had the Same Problem. Try to lower the printing range and the printing speed.
Helped for me

**Comment by ActualVoidDiver** [comment] 2022-02-06 15:30
> Hi, Had the Same Problem. Try to lower the printing range and the printing speed. Helped for me

My printing range is 2, and the printing speed is 8, which is slower than the default printing speed, pretty sure.
Is there a value for the printing range and the printing speed that you would recommend?

**Comment by aleksilassila** [comment] 2022-12-07 22:16
All is good in 3.0 (hopefully)

**Closed by aleksilassila** 2022-12-07 22:16 UTC
